dist: trusty
language: node_js
node_js:
  - '0.10'
sudo: required
notifications:
  email:
#    - aaron.steurbaut@geosolutions.be
#    - maarten.taeymans@geosolutions.be
    - cedrik.vanderhaegen@geosolutions.be
#addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

before_install:
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

before_script:
  - grunt -v jshint
  - export TZ=Europe/Brussels
  - "export DISPLAY=:99.0"
  - "export CHROME_BIN=chromium-browser"
  - "sh -e /etc/init.d/xvfb start"

script:
  - grunt test