dist: trusty
language: node_js
node_js:
  - 'lts/*'
sudo: required
notifications:
  email:
    - cedrik.vanderhaegen@vlaanderen.be
addons:
  chrome: stable

install:
  - npm install

before_script:
  - grunt -v jshint
  - export TZ=Europe/Brussels
before_install:
  - nvm install 8.12.0
  - nvm use 8.12.0
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Send coverage data to Coveralls
after_script: "cat ./lcov.info | ./node_modules/coveralls/bin/coveralls.js"