dist: xenial
language: node_js
node_js:
  - 'lts/*'
sudo: required
notifications:
  email:
    - cedrik.vanderhaegen@vlaanderen.be
install:
  - npm install
  - bower install
before_script:
  - export TZ=Europe/Brussels
before_install:
  - nvm install 11.2.0
  - nvm use 11.2.0
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - grunt jshint

