dist: trusty
language: node_js
node_js:
  - '0.10'
sudo: required
notifications:
  email:
    - cedrik.vanderhaegen@vlaanderen.be
addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

install:
  - npm install

before_script:
  - grunt -v jshint
  - export TZ=Europe/Brussels
  - "export DISPLAY=:99.0"
  - "export CHROME_BIN=chromium-browser"
  - "sh -e /etc/init.d/xvfb start"


# Send coverage data to Coveralls
after_script: "cat ./lcov.info | ./node_modules/coveralls/bin/coveralls.js"