dist: Jammy
language: node_js
node_js:
  - '18.16.0'
sudo: required
notifications:
  email:
    - cedrik.vanderhaegen@vlaanderen.be
install:
  - npm install
  - bower install
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - grunt jshint

